export const ESTATE_HAS_ERRORED = 'ESTATE_HAS_ERRORED'
export const ESTATE_IS_LOADING = 'ESTATE_IS_LOADING'
export const ESTATE_FETCH_DATA_SUCCESS = 'ESTATE_FETCH_DATA_SUCCESS'

export const ESTATES_HAS_ERRORED = 'ESTATES_HAS_ERRORED'
export const ESTATES_IS_LOADING = 'ESTATES_IS_LOADING'
export const ESTATES_FETCH_DATA_SUCCESS = 'ESTATES_FETCH_DATA_SUCCESS'
