export const ESTATE_HAS_ERRORED = 'ESTATE_HAS_ERRORED'
export const ESTATE_IS_LOADING = 'ESTATE_IS_LOADING'
export const ESTATE_FETCH_DATA_SUCCESS = 'ESTATE_FETCH_DATA_SUCCESS'

export const PLACES_HAS_ERRORED = 'PLACES_HAS_ERRORED'
export const PLACES_IS_LOADING = 'PLACES_IS_LOADING'
export const PLACES_FETCH_DATA_SUCCESS = 'PLACES_FETCH_DATA_SUCCESS'
