export const ESTATE_HAS_ERRORED = 'ESTATE_HAS_ERRORED'
export const ESTATE_IS_LOADING = 'ESTATE_IS_LOADING'
export const ESTATE_FETCH_DATA_SUCCESS = 'ESTATE_FETCH_DATA_SUCCESS'

export const HOUSE_HAS_ERRORED = 'HOUSE_HAS_ERRORED'
export const HOUSE_IS_LOADING = 'HOUSE_IS_LOADING'
export const HOUSE_FETCH_DATA_SUCCESS = 'HOUSE_FETCH_DATA_SUCCESS'

export const PARISH_HAS_ERRORED = 'PARISH_HAS_ERRORED'
export const PARISH_IS_LOADING = 'PARISH_IS_LOADING'
export const PARISH_FETCH_DATA_SUCCESS = 'PARISH_FETCH_DATA_SUCCESS'

export const TOWN_HAS_ERRORED = 'TOWN_HAS_ERRORED'
export const TOWN_IS_LOADING = 'TOWN_IS_LOADING'
export const TOWN_FETCH_DATA_SUCCESS = 'TOWN_FETCH_DATA_SUCCESS'

export const PERSON_HAS_ERRORED = 'PERSON_HAS_ERRORED'
export const PERSON_IS_LOADING = 'PERSON_IS_LOADING'
export const PERSON_FETCH_DATA_SUCCESS = 'PERSON_FETCH_DATA_SUCCESS'

export const PLACES_HAS_ERRORED = 'PLACES_HAS_ERRORED'
export const PLACES_IS_LOADING = 'PLACES_IS_LOADING'
export const PLACES_FETCH_DATA_SUCCESS = 'PLACES_FETCH_DATA_SUCCESS'

export const TITLE_HAS_ERRORED = 'TITLE_HAS_ERRORED'
export const TITLE_IS_LOADING = 'TITLE_IS_LOADING'
export const TITLE_FETCH_DATA_SUCCESS = 'TITLE_FETCH_DATA_SUCCESS'
export const TITLES_HAS_ERRORED = 'TITLES_HAS_ERRORED'
export const TITLES_IS_LOADING = 'TITLES_IS_LOADING'
export const TITLES_FETCH_DATA_SUCCESS = 'TITLES_FETCH_DATA_SUCCESS'
